update docker image references to live tags
senaite/senaite.docker pull request #18
Opened 2022-12-23 01:02 UTC by cleary

Hi @ramonski

refs #16 - the issue was raised because it seem like the default docker-compose.yml should reference a working dockerhub image tag

This patch provides that -

Regards, 
Bernie

2022-12-23 17:05 UTC, ramonski requested changes
Hi @cleary,
Thanks for your PR and apologies for the misunderstanding!
Would you mind to change the tags for the tagged folders accordingly?
Thanks!

2022-12-23 17:05 UTC, ramonski commented on 2.3.0/docker-compose.yml
> +    image: senaite/senaite:edge
Please use the tag `senaite/senaite:2.3.0` here

2022-12-23 17:05 UTC, ramonski commented on 2.2.0/docker-compose.yml
> +    image: senaite/senaite:edge
Please use the tag `senaite/senaite:2.2.0` here

2022-12-28 09:11 UTC, cleary commented
That should be done - thanks :)

2022-12-28 19:42 UTC, ramonski approved these changes
Thanks @cleary!

2022-12-28 19:43 UTC, merged